tap "adoptopenjdk/openjdk"
tap "homebrew/cask"
tap "homebrew/core"
tap "wix/brew"

brew "curl"
brew "awscli"
brew "serverless"
brew "jq"
brew "libpng"
brew "nvm"
brew "watchman"
brew "zsh"
brew "git"
brew "go"
brew "applesimutils"

cask "iterm2"
cask "spectacle"
cask "keycastr"
cask "visual-studio-code"
# cask "android-studio"
cask "adoptopenjdk8"
# cask "agenda"
cask "drawio"
cask "postico"
cask "brave-browser"
# cask "firefox"
# cask "google-chrome"
# cask "google-drive"
# cask "cloudapp"
# cask "dropbox"
cask "hyper"
cask "loom"
cask "notion"
cask "spotify"
cask "slack"
cask "1password"
cask "postman"
cask "zoom"
